### ISSUE TITLE
Fix pkgdown configuration for reference

### ISSUE THREAD

**Issue by maelle** [ropensci/skynet#10]
Some topics are missing from the configuration file.

```r
 Error in check_missing_topics(rows, pkg) : 
  All topics must be included in reference index
• Missing topics: MetroFull, MetroLookup, OD_Sample, aircraft_type, airportCode, airportCodeFull, airportMaster, carriers, download_db1b, download_ontime, download_t100, download_t100_int, import_ontime, make.netInt, make_net_trip, netImport, nodeStatsMetro, skynet_example
```

Note that for topics you do not want to include in the index you can create an "internal" section https://pkgdown.r-lib.org/reference/build_reference.html?q=internal#missing-topics

To check all topics are listed, after editing the configuration file you can run `pkgdown::check_pkgdown()`.

**Comment by maelle** [comment]
@FilipeamTeixeira friendly reminder :smile_cat:

**Comment by FilipeamTeixeira** [comment]
@maelle I'll do it this weekend as I'm currently starting a new job. Thank you a lot for this.

**Comment by maelle** [comment]
Thank you and congrats on the new job!!

**Comment by maelle** [comment]
:wave: @FilipeamTeixeira friendly reminder :smile_cat:
