### ISSUE TITLE
igraph 1.3.0 will break `skynet` unit tests

### ISSUE THREAD

**Issue by ntamas** [ropensci/skynet#8]
Dear Skynet team,

I am writing you to let you know that `igraph` 1.3.0 will introduce a change that causes some of the `skynet` unit tests to fail. In particular, calling `length(g)` on an `igraph` graph `g` in earlier versions returned `10` unconditionally, which was considered a bug by many (see https://github.com/igraph/rigraph/issues/427 ). From `igraph` 1.3.0, `length(g)` will be consistent with the `[[` indexing operator; since `[[` indexes into the adjacency list of the graph, `length(g)` will return the number of vertices in the graph.

Your unit tests check whether `length(g)` is `10` and I'm not sure what's the purpose of that. If you would like to test the number of vertices, use `vcount(g)` instead and compare it with the expected vertex count. If you would like to know whether you are working with an igraph graph, use `class(g)` instead and check whether the result is `"igraph"`.

**Comment by maelle** [comment]
@FilipeamTeixeira is help needed to tackle this?

**Comment by FilipeamTeixeira** [comment]
@maelle . Thank you a lot. I'll fix it this week.

**Comment by maelle** [comment]
Thank you @FilipeamTeixeira!

**Comment by FilipeamTeixeira** [comment]
@maelle @ntamas Thank you for letting me know this and for your help. The length issue wasn't affecting skynet, but rather only the test part for CRAN. Nevertheless it should be working now.

**Comment by maelle** [comment]
@FilipeamTeixeira Thanks for the fix and for the update!
